pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               sh script: '''
	       	    echo "I am in build step"
		    chmod +x gradlew
		    ./gradlew build
               '''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
	    steps{
	   	sh script: '''
		echo "I am in Static Code Analysis step"
		./gradlew sonarqube -Dsonar.projectKey=mogsaqlain -Dsonar.organization=skadiri -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=eb86dd433082444f559753c66cc65962ccd1d10f''',
            	label: "Running Static Code Analysis"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                echo "Building DockerImage"
                sh "docker build -t mog -f .infra/docker/Dockerfile ."
	    }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
		    docker login -u "saqlainkadiri" -p "dummypassword"
                    echo "I am Pubishing DockerImage"
		    docker tag mog:latest saqlainkadiri/mog:latest
                    docker push saqlainkadiri/mog:latest
                ''',
            label: "Publishing Docker Image"
            	}
	}
    }
    post{
    	always{
		deleteDir()
	}
    }
}
