	pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               sh script: '''
	       	    echo "I am in build step"
		    chmod +x gradlew
		    ./gradlew build
               '''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
	    environment {
                scannerHome = tool 'SonarQubeScanner'
    	    }
    	    steps {
        	withSonarQubeEnv('sonarqube') {
            	    sh "${scannerHome}/bin/sonar-scanner"
                }
            	timeout(time: 10, unit: 'MINUTES') {
            	    waitForQualityGate abortPipeline: true
            	}
            }
        }
        stage('Build DockerImage')
        {
            steps {
                echo "Building DockerImage"
                sh "docker build -t mog -f .infra/docker/Dockerfile ."
	    }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
		    docker login -u "saqlainkadiri" -p "dummypassword"
                    echo "I am Pubishing DockerImage"
		    docker tag mog:latest saqlainkadiri/mog:latest
                    docker push saqlainkadiri/mog:latest
                ''',
            label: "Publishing Docker Image"
            	}
	}
    }
    post{
    	always{
		deleteDir()
	}
    }
}
